window._tx=function(d){d.lib=function(b){function q(){try{var a=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(k){a=!1}}a||"undefined"==typeof XMLHttpRequest||(a=new XMLHttpRequest);return a}b.txqpid=null;b.foadh=null;b.cdh=null;b.ddh=".hybrid.ai";b.aldhs=[".adhello.pl",".rtbdro.id",".iclicks.io"];b.ppb=!1;var l=function(a){a.stringify=function(e){return window.JSON&&window.JSON.stringify?window.JSON.stringify(e):a.encode(e)};a.parse=function(e){return window.JSON&&
window.JSON.parse?window.JSON.parse(e):a.decode(e)};a.encode=function(a){switch(typeof a){case "string":return"'"+a+"'";case "number":return isFinite(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";var e=[];if("[object Array]"===Object.prototype.toString.apply(a)){for(var b=0;b<a.length;b++)e[b]=this.encode(a[b])||"null";return"["+e.join(",")+"]"}for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var f=this.encode(a[b]);f&&e.push("'"+b+"':"+f)}return"{"+
e.join(",")+"}"}};a.decode=function(a){return null!==a&&"string"===typeof a&&/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,"@").replace(/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?(new Function("return "+a))():null};return a}(d.JSON||{}),u=function(){var a={};try{location&&location.href&&4<location.href.length&&1E3>location.href.length&&(a.Url=location.href),document&&document.referrer&&4<document.referrer.length&&
1E3>document.referrer.length&&(a.Referrer=document.referrer),a.Language=navigator?navigator.language||navigator.browserLanguage:"",screen&&Number(screen.width)===screen.width&&0===screen.width%1&&Number(screen.height)===screen.height&&0===screen.height%1&&0<screen.width&&2147483647>screen.width&&0<screen.height&&2147483647>screen.height&&(a.ScreenWidth=screen.width,a.ScreenHeight=screen.height),a.TimezoneOffset=(new Date).getTimezoneOffset()/60}catch(e){}return a},v=function(a,e,b){a.addEventListener?
a.addEventListener(e,b,!1):a.attachEvent&&a.attachEvent("on"+e,b)},x=function(a,e){var b=document.createElement("script");b.type="text/javascript";b.async=e;b.src=a;(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(b)},z=function(a){if(window.Image)var b=new Image;else document&&(b=document.createElement("img"),b.width=1,b.height=1);if(b)b.onload=b.onerror=function(){b.onload=null;b.onerror=null},b.src=a;else{var k=q();k&&(k.open("GET",a,!0),k.send(null))}},
A=function(){var a={apl:null,cs:"",pcs:[],vcs:[]},b=window.__tcfapi;if(!b)try{for(var k,c=window;c;){try{if(c.frames.__tcfapiLocator){k=c;break}}catch(g){}if(c===window.top)break;c=c.parent}if(k){var f={};b=function(a,b,e,c){var g=Math.random()+"";a={__tcfapiCall:{command:a,parameter:c,version:b,callId:g}};f[g]=e;k.postMessage(a,"*")};v(window,"message",function(a){a="string"===typeof a.data?l.parse(a.data):a.data;a.__tcfapiReturn&&(a=a.__tcfapiReturn,"function"===typeof f[a.callId]&&(f[a.callId](a.returnValue,
a.success),delete f[a.callId]))},!1)}}catch(g){}if(b)try{c=function(b,e){if(b){a.apl=a.apl||b.gdprApplies;a.cs=a.cs||b.tcString;if(b.purpose&&b.purpose.consents)for(var g in b.purpose.consents)b.purpose.consents[g]&&-1===a.pcs.indexOf(g)&&a.pcs.push(g);if(b.vendor&&b.vendor.consents)for(var c in b.vendor.consents)b.vendor.consents[c]&&-1===a.vcs.indexOf(c)&&a.vcs.push(c)}},b("getTCData",2,c),b("getTCData",1,c)}catch(g){}b=window.__cmp;if(!b)try{var d;for(c=window;!d;){try{c.frames.__cmpLocator&&(d=
c)}catch(g){}if(c===window.top)break;c=c.parent}if(d){var m={};b=function(a,b,e){var g=Math.random()+"";a={__cmpCall:{command:a,parameter:b,callId:g}};m[g]=e;d.postMessage(a,"*")};v(window,"message",function(a){a="string"===typeof a.data?l.parse(a.data):a.data;a.__cmpReturn&&(a=a.__cmpReturn,m[a.callId](a.returnValue,a.success),delete m[a.callId])},!1)}}catch(g){}if(b)try{c=function(b,e){if(b){a.apl=a.apl||b.gdprApplies;a.cs=a.cs||b.consentData||b.metadata||"";if(b.purposeConsents)for(var c in b.purposeConsents)b.purposeConsents[c]&&
-1===a.pcs.indexOf(c)&&a.pcs.push(c);if(b.vendorConsents)for(var d in b.vendorConsents)b.vendorConsents[d]&&-1===a.vcs.indexOf(d)&&a.vcs.push(d)}},b("getConsentData",null,c),b("getVendorConsents",null,c)}catch(g){}return a},n=function(a){return"foadh="+encodeURIComponent(a||"")},p=function(){var a=A();return"gapl="+(null!=a.apl?a.apl?"1":"0":"")+"&cs="+a.cs+"&pcs="+a.pcs.join("_")+"&vcs="+a.vcs.join("_")},y=function(){var a=document.getElementsByTagName("script");if(a)for(var e=0;e<a.length;e++){var d=
a[e].src;if(d)for(var c=0;c<b.aldhs.length;c++){var f=b.aldhs[c];if(-1<d.indexOf(f)&&(-1<d.indexOf("txsp.js")||-1<d.indexOf("advertiser.js")))return f}}return b.ddh},r=function(){return"https://dss"+(b.cdh||y())+"/"},t=function(a){b.ppb?window.setTimeout(function(){t(a)},1E3):(b.ppb=!0,z(a),window.setTimeout(function(){b.ppb=!1},1E3))},w=function(a,b,d,c,f,h,m,g,l){a="Pixel/Track2?pid="+(a||"")+"&bobid="+(b||"")+"&evt="+encodeURIComponent(d||"")+"&cost="+encodeURIComponent(c||"")+"&text="+encodeURIComponent(f||
"")+"&ltm="+(m||!1)+"&cnt="+(h||"")+"&url="+encodeURIComponent(g.Url||"")+"&rf="+encodeURIComponent(g.Referrer||"")+"&lng="+(g.Language||"")+"&tz="+(g.TimezoneOffset||"")+"&sw="+(g.ScreenWidth||"")+"&sh="+(g.ScreenHeight||"")+"&"+n(l)+"&"+p()+"&r=";t(r()+a)},B=function(a,b,d,c,f,h){a="Pixel/DynamicTrack?pid="+(a||"")+"&bobid="+(b||"")+"&evt="+encodeURIComponent(d||"")+"&cnt="+encodeURIComponent(c||"")+"&url="+encodeURIComponent(f.Url||"")+"&rf="+encodeURIComponent(f.Referrer||"")+"&lng="+(f.Language||
"")+"&tz="+(f.TimezoneOffset||"")+"&sw="+(f.ScreenWidth||"")+"&sh="+(f.ScreenHeight||"")+"&"+n(h)+"&"+p()+"&r=";t(r()+a)},C=function(a,b,d,c,f,h,m){a="Pixel/Identify2?pid="+(a||"")+"&bobid="+(b||"")+"&cstid="+(d||"")+"&icnt="+(c||"")+"&ucnt="+(f||"")+"&url="+encodeURIComponent(h.Url||"")+"&rf="+encodeURIComponent(h.Referrer||"")+"&lng="+(h.Language||"")+"&tz="+(h.TimezoneOffset||"")+"&sw="+(h.ScreenWidth||"")+"&sh="+(h.ScreenHeight||"")+"&"+n(m)+"&"+p()+"&r=";t(r()+a)};b.txqhnd=function(a){if(a&&
"string"===typeof a[0]){var e=a[0].toLowerCase();if("createpixel"===e)"string"==typeof a[1]&&(b.txqpid=a[1],a[2]&&(b.foadh=1),window.setTimeout(function(){var a=n(b.foadh),c=p();x("https://emd.hybrid.ai/plgt.js?fbpid="+b.txqpid+"&"+a+"&"+c,!0)},2E3));else if("track"===e){if("string"===typeof a[1]){var k=a[1],c=null;try{a[2]&&(c=encodeURIComponent(l.stringify(a[2])))}catch(m){}var f=u();"pageview"===k.toLowerCase()?(w(b.txqpid,d.HybridAiBobId,k,null,null,c,!1,f,b.foadh),a=n(b.foadh),e=p(),x(r()+"Pixel/TrackTp?pid="+
(b.txqpid||"")+"&"+a+"&"+e,!0),window.setTimeout(function(){w(b.txqpid,d.HybridAiBobId,k,null,null,c,!0,f,b.foadh)},15E3)):w(b.txqpid,d.HybridAiBobId,k,a[3],a[4],c,!1,f,b.foadh)}}else if("track_d"===e){if("string"===typeof a[1]&&"string"===typeof a[2]){e=a[1];a=a[2];var h=u();B(b.txqpid,d.HybridAiBobId,e,a,h,b.foadh)}}else if("identify"===e&&"string"===typeof a[1]){h=e=null;try{a[2]&&(e=encodeURIComponent(l.stringify(a[2]))),a[3]&&(h=encodeURIComponent(l.stringify(a[3])))}catch(m){}C(b.txqpid,d.HybridAiBobId,
a[1],e,h,u(),b.foadh)}}};b.txq=function(a){this.push(a)};b.txq.prototype.push=function(a){b.txqhnd(a)};b.txqi=function(){window._txq=window._txq||[];if(window._txq)for(var a in window._txq)window._txq.hasOwnProperty(a)&&b.txqhnd(window._txq[a]);"complete"==document.readyState?window._txq=new b.txq(window._txq):v(document,"readystatechange",function(){window._txq=new b.txq(window._txq)});b.cdh=y()};return b}(d.lib||{});d.lib.txqi();d.sendPixel=function(b){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track",
"PageView"])};d.sendEvent=function(b,q){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track",q])};d.sendProductView=function(b,q,l){d.lib.txqhnd(["createPixel",b]);d.lib.txqhnd(["track","ViewContent",{content_type:"product",content_ids:[l]}])};d.MarkVisitor=function(){};d.sendAudience=function(){};d.sendAudienceTags=function(){};return d}(window._tx||{});
